version: "3.9"
services:
  api-gateway:
    image: npailax64/asistente_ia-webserver
    ports:
      - "20000:20000"
    networks:
      - api-gateway

networks:
  api-gateway:
    name: chatbot_network
    external: true