version: "3.9"
services:
  api-gateway:
    image: npailax64/asistente_ia-api_gateway
    ports:
      - "20000:20000"
    networks:
      - chatbot_network

networks:
  chatbot_network:
    name: chatbot_network
    external: true