version: "3.9"
services:
  assistant-app:
    image: ${IMAGE_REPO}/asistente_ia-assistant_app
    ports:
      - "8080:80"
    environment:
      - API_URL=${API_URL}
    networks:
      - assistant_network

networks:
  assistant_network:
      external: true
      name: ${NETWORK_NAME}
