version: '3.9'
services:
  chat-log:
    image: ${IMAGE_REPO}/assistant-chat_log_service
    ports:
      - ${CHAT_LOG_SERVICE_EXTERNAL_PORT}:8080
    depends_on:
      - chat-log-mongo
    networks:
      - assistant_network

  chat-log-mongo:
    image: mongo:4.4.18
    ports:
      - ${CHAT_LOG_DATABASE_EXTERNAL_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - chat-log-mongodata:/data/db
    networks:
      - assistant_network

volumes:
  chat-log-mongodata:

networks:
  assistant_network:
      external: true
      name: ${NETWORK_NAME}
