version: "3.9"
services:
  chatbot-app:
    image: npailax64/asistente_ia-chatbot_app
    ports:
      - "8080:80"
    networks:
      - chatbot_network

networks:
  chatbot_network:
    name: chatbot_network
    external: true