version: "3.9"
services:
  api-gateway:
    image: ${IMAGE_REPO}/asistente_ia-api_gateway
    ports:
      - "20000:20000"
    networks:
      - assistant_network

networks:
  assistant_network:
      external: true
      name: ${NETWORK_NAME}
