version: "3.9"
services:
  assistant-db:
    image: postgres:15.4-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - ${ASSISTANT_DATABASE_EXTERNAL_PORT}:5432
    volumes: 
      - assistant-db:/var/lib/postgresql/data
      - ./db/assistant-init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - assistant_network
  
  assistant:
    hostname: ${ASSISTANT_SERVICE_HOSTNAME}
    image: ${IMAGE_REPO}/assistant-assistant_service
    depends_on:
      assistant-db:
        condition: service_healthy
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DEBUG: 'false'
      DB_HOST: assistant-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    ports:
      - ${ASSISTANT_SERVICE_EXTERNAL_PORT}:8080
    networks:
      - assistant_network

volumes:
  assistant-db:
    driver: local

networks:
  assistant_network:
      external: true
      name: ${NETWORK_NAME}
