version: "3.9"
services:
  chatbot-app:
    image: npailax64/asistente_ia-chatbot_app
    environment:
      CHATBOT_SERVICE_HOSTNAME: 'localhost'
      CHATBOT_SERVICE_PORT: '1234'
      DEBUG: 'false'
    ports:
      - "8080:80"
    networks:
      - chatbot-app

networks:
  chatbot-app:
    name: chatbot_network
    external: true