version: "3.9"
services:
  api-gateway:
    image: ${IMAGE_REPO}/assistant-api_gateway_service
    ports:
      - ${API_GATEWAY_SERVICE_EXTERNAL_PORT}:20000
    networks:
      - assistant_network

networks:
  assistant_network:
      external: true
      name: ${NETWORK_NAME}
