version: "3.9"
services:
  api-gateway:
    image: npailax64/asistente_ia-api_gateway
    ports:
      - "20000:20000"
    networks:
      - kc_assistant_network

networks:
  kc_assistant_network:
    external: true