version: "3.9"
services:
  assistant-app:
    image: npailax64/asistente_ia-assistant_app
    ports:
      - "8080:80"
    networks:
      - assistant_network

networks:
  assistant_network:
    external: true